esphome:
  name: aire-felito
  friendly_name: Aire Felito

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "Dv/Htvi+tCOtaATOcRcxVJdsF84vtf3QDsaOQh6ylUk="

ota:
  password: "464464a6c630ea65443b303246bdacf5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aire-Felito Fallback Hotspot"
    password: "GtoauumEiXwu"

captive_portal:

remote_receiver:
  id: "rece"
  pin:
    number: GPIO1
    inverted: True
  dump: all
  on_coolix:
    - logger.log:
        format: "The tdata received %s"
        args: ["id(rece).state"]
