esphome:
  name: aires
  friendly_name: Aires

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8+gKtrp4QvFEa2tGW+0a0XFW20RBbtyBX7XON5FF798="

ota:
  password: "c0c8249a9067dade22f8187c5af7b94f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aires Fallback Hotspot"
    password: "lZpog56gemhE"
# Example configuration entry
globals:
  - id: aire_global
    type: 'bool'
    restore_value: no
    initial_value: 'false'
# Example configuration entry
binary_sensor:
  - platform: gpio
    pin: GPIO41
    name: "Living Room Window"
    on_click:
      min_length: 1ms
      max_length: 49ms
      then:
        - remote_transmitter.transmit_coolix:
            first: 0xB27BE0
          # - id(aire_global) = false;
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - remote_transmitter.transmit_coolix:
            first: 0b0000
        # - id(aire_global) = true;


captive_portal:
remote_transmitter:
  pin: GPIO2
  carrier_duty_percent: 50%

climate:
  - platform: coolix       # adjust to match your AC unit!
    name: "alice_leti"
web_server:
    port: 80