esphome:
  name: aire-felito
  friendly_name: Aire Felito

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8+gKtrp4QvFEa2tGW+0a0XFW20RBbtyBX7XON5FF798="
  services:
    - service: toggle_light
      then:
        - remote_transmitter.transmit_coolix:
            first: 0xB5F5A5
            second: 0xB5F5A5

ota:
  password: "c0c8249a9067dade22f8187c5af7b94f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aires Fallback Hotspot"
    password: "lZpog56gemhE"

binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO41
      # inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      then:
        if:
          condition:
            lambda: "return id(aire).mode==CLIMATE_MODE_OFF;"
          then:
            - climate.control:
                id: aire
                mode: "COOL"
                target_temperature: 19

          else:
            - climate.control:
                id: aire
                mode: "OFF"
  # - platform: template
  #   name: "Toogle light"
  #   icon: "mdi:lightbulb"
  #   on_press:
  #     remote_transmitter.transmit_coolix:
  #       first: 0xB5F5A5
  #       second: 0xB5F5A5

light:
  - platform: binary
    id: ac_light
    name: "AC Light"
    output: light_output
    restore_mode: RESTORE_AND_OFF

output:
  - id: light_output
    platform: template
    type: binary
    # inverted: true
    write_action:
      remote_transmitter.transmit_coolix:
        first: 0xB5F5A5
        second: 0xB5F5A5

captive_portal:
remote_transmitter:
  pin: GPIO2
  carrier_duty_percent: 50%

# external_components:
#   - source: github://Jorre05/remote_receiver
#     components: [remote_receiver]

# remote_receiver:
#   pin:
#     number: GPIO1
#     inverted: true
#     mode:
#       input: true
#       pullup: true
#   rmt_channel: 4
#   dump: coolix

climate:
  - platform: coolix # adjust to match your AC unit!\
    id: "aire"
    name: "Aire Felito"
    on_state:
      - lambda: |-
          if (x.mode != CLIMATE_MODE_OFF) {
            id(ac_light).turn_on();
          }else {
            id(ac_light).turn_off();

          }

web_server:
  port: 80
