esphome:
  name: aires
  friendly_name: Aires

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8+gKtrp4QvFEa2tGW+0a0XFW20RBbtyBX7XON5FF798="

ota:
  password: "c0c8249a9067dade22f8187c5af7b94f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aires Fallback Hotspot"
    password: "lZpog56gemhE"

binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO41
      # inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      then:
        if:
          condition:
            lambda: "return id(aire).mode==CLIMATE_MODE_OFF;"
          then:
            climate.control:
              id: aire
              mode: "COOL"
          else:
            climate.control:
              id: aire
              mode: "OFF"

button:
  - platform: template
    name: "Toogle light"
    on_press:
      remote_transmitter.transmit_coolix:
        first: 0xB5F5A5
        second: 0xB5F5A5

captive_portal:
remote_transmitter:
  pin: GPIO2
  carrier_duty_percent: 50%

# remote_receiver:
#   pin: GPIO1
#   carrier_duty_percent: 50%

climate:
  - platform: coolix # adjust to match your AC unit!\
    id: "aire"
    name: "Aire Alice y Leti"
web_server:
  port: 80
