esphome:
  name: aire-felito
  friendly_name: Aire Felito

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "Dv/Htvi+tCOtaATOcRcxVJdsF84vtf3QDsaOQh6ylUk="

ota:
  password: "464464a6c630ea65443b303246bdacf5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aire-Felito Fallback Hotspot"
    password: "GtoauumEiXwu"

captive_portal:
binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO41
      mode:
        input: true
        pullup: true
    on_press:
      then:
        if:
          condition:
            lambda: "return id(aire).mode==CLIMATE_MODE_OFF;"
          then:
            climate.control:
              id: aire
              mode: "COOL"
          else:
            climate.control:
              id: aire
              mode: "OFF"

climate:
  - platform: coolix # adjust to match your AC unit!\
    id: "aire"
    name: "Aire Felito"
web_server:
  port: 80